### ISSUE TITLE
Certs are only valid for 90 days

### ISSUE THREAD

**Issue by therealparmesh** [digitalocean/OpenVPN-Pihole#7]
Should we make this configurable?

**Comment by CrashenX** [comment]
I'm not immediately aware of a way to make it configurable and a one click, but open to the idea of configuration options.

You could reconfigure via SSHing in. I'd lean towards create a new one which will have updates and delete old one.

**Comment by banagale** [comment]
First, thank you for this--it is a great product.

Can you give any feedback on the necessity of the 90 day default? I saw the reason is to ensure the software is updated. Is this related to the entire preconfigured digital ocean droplet, or specific dependencies of the primary tools?

While it is easy to build a new droplet and create new profiles for devices, it would be good to know if one could manually update an existing droplet and feel confident things are up to date.

**Comment by CrashenX** [comment]
Thanks!

The 90 day default is not a necessity. It was a conscious choice to help make sure folks are running up to date software and encourage cattle not pets.

You can manually update an existing droplet. I would encourage that you keep all the software up to date if you plan to keep it around for an extended time.

The primary use case I had in mind when creating this was for people on the go who would spin up a Droplet with OpenVPN+Pihole before leaving home, connect to it, and tear it down when back home. I use [these scripts](https://github.com/digitalocean/OpenVPN-Pihole/tree/master/client-tools) to do just that,  usually in just a few minutes (copy my password from password vault, run termux shortcut from home screen on mobile, paste key, copy client ovpn file to Downloads, import into openvpn, delete from Downloads, connect). That said, this becomes a bit more annoying if you are using the same VPN for more than one device and you need to generate additional ovpn files and get them to said devices.

**Comment by kindaran** [comment]
I'm in the camp that was looking for a permanent server. I'm not really sure what's going to happen in 90 days (I'm new to all this). Will VPN no longer work? And when talking about 'reconfiguring" are you talking about doing something with the certification? As for "updating" my intention is to setup unattended apt updates (I'm assuming that takes care of that concern).

**Comment by CrashenX** [comment]
The certificate will expire in 90 days from creation so you'll likely see a certificate error when you attempt to connect after 90 days. You can create new certificates and set the expiration to what makes sense for your use case. Then you can use those certificates to connect. I won't provide instructions as there are better guides online, and I'd want to test them myself before recommending one.

Unattended apt updates might already be configured. If not, yes, that is a good step. I won't try to enumerate all the considerations you might want to make for maintaining a "pet", as I'll likely miss something important and there are better references out there.

When you create a new droplet it updates everything and creates new certificates. This eliminates the need to "maintain" a pet.

I think the real opportunity for improvement here, is to make it easier to spin up and connect to the VPN on demand / periodically spin up a new one and easily connect for all clients. I think this could be done fairly easily with a script on each client. As long as each client had its ssh key added to the droplet, you could activate the script to connect to the target (probably via DNS) and retrieve the new certificate. I think to make this really successful it'd need to be an app so it could integrate with biometrics.

**Comment by CrashenX** [comment]
On another note. If you want a persistent OpenVPN + PiHole server for your home, buy a Raspberry Pie or some other low powered device and set it up in your home. This project is designed for a mobile use case.

**Comment by kindaran** [comment]
I appreciate the comments. I'm not going to complain too hard about a system setup for a specific use case. 

The setup/teardown is pretty simple. Not too much work to swap out ovpn client files and I have even roughly scripted out setting up unattended upgrades, fail2ban, no password login, and a non-root user. So... this could be good enough.

I'll have a look at creating new certificates. Again, being new, are you talking about what I understand to be the "CA cert"? That seems to be the top level and then there's some client stuff under that.

thanks

**Comment by CrashenX** [comment]
Take a look here: https://github.com/digitalocean/OpenVPN-Pihole/blob/master/files/var/lib/cloud/scripts/per-instance/02-openvpn-install#L82-L83

That file is derived from: https://github.com/digitalocean/OpenVPN-Pihole/blob/master/files/var/lib/cloud/scripts/per-instance/02-openvpn-install#L4

I put an inquiry out to the Marketplace team to see if there is a way to configure apps based on user input to support this use case. I could probably hack it in somehow.

Alternatively, if you want to create a bash script to update the certs, I can carve out some time to review it and add it to the repo so that it's installed into the image and there are instructions upon logging in on how to run it for users that want a more persistent pet.

Also, any post-install configurations you think are valuable to add, we can take a look at adding those to the image. Just make a PR and ping me.

**Comment by CrashenX** [comment]
At the end of the day, I could just change the default and put a warning that people really ought to periodically build a new droplet. The point of making such a short renewal was to discourage long lived pets, but ultimately I don't need to enforce that.

**Comment by kindaran** [comment]
Well, I suppose that would open the door for both a long term server and anyone who wants a "'pet" server can still take it down at will. But I leave that up to you. I'd probably take a shot at the cert change but it's very new stuff for me so I don't know if I'll have success. I'll look at the links when I get some time.

**Comment by kindaran** [comment]
Not sure if this is the best place to continue this conversation. But anyway... If I'm doing this right, I ran 
`openssl x509 -text -noout -in ca.crt`
in directory /etc/openvpn/server. It shows
```
        Validity
            Not Before: Oct  3 16:52:10 2020 GMT
            Not After : Oct  1 16:52:10 2030 GMT
```
and server.crt shows
```
        Validity
            Not Before: Oct  3 16:52:10 2020 GMT
            Not After : Jan  1 16:52:10 2021 GMT
```

So I'm wondering if that means these dont expire right away or am I looking at the wrong thing?

**Comment by CrashenX** [comment]
@kindaran https://github.com/digitalocean/OpenVPN-Pihole/blob/master/files/var/lib/cloud/scripts/per-instance/02-openvpn-install#L82 sets EASYRSA_CERT_EXPIRE=90. It does NOT set EASYRSA_CA_EXPIRE.

Here's where client.crt and server.crt can be found: https://github.com/digitalocean/OpenVPN-Pihole/blob/master/files/var/lib/cloud/scripts/per-instance/03-create-client-config#L30

As you see in the information you provided above, the server.crt expires in 90 days from when you created the Droplet (January 1st). Same is true for client.crt.

The easiest change is to update L82 mentioned above to have a longer expiry and rebuild and release a new Marketplace image. Then all future builds would have a longer expiry.

I was meaning to look at this week but got deep into some other work. I might be able to look at building a new image with a longer expiry next week.

I also got some information internally about using https://www.digitalocean.com/docs/droplets/how-to/provide-user-data/ to allow setting the expiry. That would be more work but more ideal. I'll probably end up doing the latter when I get time.

**Comment by kindaran** [comment]
Thanks @CrashenX  - I figured I might be looking at the wrong thing. I had mentioned the user data thing on another of the issues posted here wondering out loud if that was a way to allow 'customization' of a server build and as I said, it would take some thinking (for me at least) to assess how viable an option and how it would work to utilize user data.

**Comment by kindaran** [comment]
@CrashenX: trying to understand the overall process of building one of these servers. Would the following be correct:
- create a basic droplet with the same config as the final server (Ubuntu 18, sizing, etc)
- on a remote machine, have this repository cloned and run the commands to setup a "fab" venv
- run fab build -H <your_build_droplet_ip_address> on a clean droplet once the testbuild works
- save snapshot as certain name (I assume in a "marketplace location"?)
- run vpn-up which creates a droplet using the above "image" or snapshot

If the above is correct then obviously vpn-up is not the place for user data. Unless the OpenVPN/PiHole config (the scripts in files) is done as part of vpn-up rather than the fabric process. At that point it seems like the entire process (from server creation to setup to final step) would be in vpn-up. What we are talking about trying to do is a dynamic build process and some aspects of that are not available until "runtime".

**Comment by CrashenX** [comment]
You should be able to run everything on your local machine to create the droplet. It's been a bit since I built this and I did it as part of a hackathon, so I don't recall the exact steps. The docs are here: https://github.com/digitalocean/marketplace-partners

**Comment by kindaran** [comment]
I did do that. Created a blank droplet and then ran the python code locally. In doing so, realized I can use my own fork and change the scripts for expiration dates. Though I would do some more testing on the results than I did yesterday before dropping my current server.

**Comment by CrashenX** [comment]
Yeah and once you create the image, you can then use it to build all future Droplets. Marketplace apps are largely just building a Droplet using a custom configured image.

That said, if you change anything and want to make a pull request, I can review it. Anything merged here can be rebuild and released for everyone.

**Comment by CrashenX** [comment]
The new image is not posted to the marketplace yet, but working to get it up there ASAP. In the meantime, you can create your own snapshot and build droplets from that: https://github.com/digitalocean/marketplace-pi-hole-vpn
